---
name: nightmayr-qt-5-15-4-2004
version: 5.15.4
base: core20
summary: Shared Qt 5.15
description: |
 This snap contains the necessary libraries required by
 Qt Applications.
confinement: strict
grade: stable
slots:
  nightmayr-qt-5-15-4-2004:
    interface: content
    read:
      - /
plugs:
  nightmayr-plasma-integration-5-2004:
    default-provider: nightmayr-plasma-integration-5-2004
    interface: content
    target: $SNAP/kf5
  nightmayr-qgnomeplatform-qt5-2004:
    default-provider: nightmayr-qgnomeplatform-qt5-2004
    interface: content
    target: /snap/nightmayr-qt-5-15-4-2004/current/qgnomeplatform
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
compression: lzo
parts:
  qt-sdk:
    plugin: nil
    stage-snaps:
      - nightmayr-qt-5-15-4-2004-sdk
    stage:
      - -usr/include
      - -usr/lib/$CRAFT_ARCH_TRIPLET/cmake
      - -usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/lib/$CRAFT_ARCH_TRIPLET/qt5/mkspecs
      - -usr/share/doc
      - -usr/share/ffmpeg/examples
      - -usr/share/pkgconfig
      - -usr/lib/qt5
      - -usr/**/*.a
      - -usr/**/*.la
      - -usr/**/*.prl