---
name: nightmayr-qt-6-3-1-2204
version: 6.3.1
base: core22
summary: Shared Qt 6
description: |
 This snap contains the necessary libraries required by
 Qt Applications.
confinement: strict
grade: stable
slots:
  nightmayr-qt-6-3-1-2204:
    interface: content
    read:
      - /
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
compression: lzo
parts:
  qt-sdk:
    plugin: nil
    stage-snaps:
      - nightmayr-qt-6-3-1-2204-sdk/latest/candidate
    stage:
      - -usr/include
      - -usr/lib/$CRAFT_ARCH_TRIPLET/cmake
      - -usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/lib/$CRAFT_ARCH_TRIPLET/qt6/mkspecs
      - -usr/share/doc
      - -usr/share/ffmpeg/examples
      - -usr/share/pkgconfig
      - -usr/lib/qt6
      - -usr/**/*.a
      - -usr/**/*.la
      - -usr/**/*.prl