---
name: nightmayr-qt-5-15-6-2204
version: 5.15.6
base: core22
summary: Shared Qt 5.15
description: |
 This snap contains the necessary libraries required by
 Qt Applications.
confinement: strict
grade: stable
slots:
  nightmayr-qt-5-15-6-2204:
    interface: content
    read:
      - /
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
compression: lzo
parts:
  qt-sdk:
    plugin: nil
    stage-snaps:
      - nightmayr-qt-5-15-6-2204-sdk
    stage:
      - -usr/include
      - -usr/lib/$CRAFT_ARCH_TRIPLET/cmake
      - -usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/lib/$CRAFT_ARCH_TRIPLET/qt5/mkspecs
      - -usr/share/doc
      - -usr/share/ffmpeg/examples
      - -usr/share/pkgconfig
      - -usr/lib/qt5
      - -usr/**/*.a
      - -usr/**/*.la
      - -usr/**/*.prl
  command-chain:
    source: https://github.com/snapcore/snapcraft-desktop-integration.git
    source-type: git
    source-subdir: qt5
    plugin: make
    override-pull: |
      craftctl default
      find $CRAFT_PROJECT_DIR/snap/local/patches -type f -print0 | sort -z | xargs -r0 git apply
    make-parameters:
      - PLATFORM_PLUG=$CRAFT_PROJECT_NAME